version: '3'
services:
  wordpress:
    image: wordpress:4
    ports:
      - '8080:80'
    networks:
      - wpnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      WORDPRESS_DB_PASSWORD: mypasswd

  mysql:
    image: mysql:5.7.22
    networks:
      - wpnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: mypasswd

networks:
  wpnet:
